// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "BarCodeScanner",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "BarCodeScanner",
            targets: ["AppModule"],
            bundleIdentifier: "AdityaGaba-adityagaba.onmicrosoft.com.BarCodeScanner",
            teamIdentifier: "2SQ4M5N586",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .twoPeople),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "The app needs camera access to scan barcode and text")
            ],
            appCategory: .medical
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)